apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo
  labels:
    training: kubernetes-demo
spec:
  selector:
    app: hw-demo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP